// <auto-generated>
// Code generated by luis:generate:cs
// Tool github: https://github.com/microsoft/botframework-cli
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;

namespace RobinhoodBot.Model
{
    public partial class StockMarketCognitiveModel : IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            AskForBuyRecommendation,
            AskForSellRecommendation,
            BuyAssets,
            Decline,
            None,
            SellAssets
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Lists
            public string[][] asset_type;


            // Composites
            public class _InstanceAsset
            {
                public InstanceData[] asset_name;
            }
            public class AssetClass
            {
                public string[] asset_name;
                [JsonProperty("$instance")]
                public _InstanceAsset _instance;
            }
            public AssetClass[] asset;

            public class _InstancePurchase_details
            {
                public InstanceData[] number_of_stocks;
                public InstanceData[] asset;
                public InstanceData[] price;
            }
            public class Purchase_detailsClass
            {
                public string[] number_of_stocks;
                public AssetClass[] asset;
                public string[] price;
                [JsonProperty("$instance")]
                public _InstancePurchase_details _instance;
            }
            public Purchase_detailsClass[] purchase_details;

            // Instance
            public class _Instance
            {
                public InstanceData[] asset;
                public InstanceData[] asset_name;
                public InstanceData[] asset_type;
                public InstanceData[] number_of_stocks;
                public InstanceData[] price;
                public InstanceData[] purchase_details;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<StockMarketCognitiveModel >(
                JsonConvert.SerializeObject(
                    result,
                    new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, Error = OnError }
                )
            );
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        private static void OnError(object sender, ErrorEventArgs args)
        {
            // If needed, put your custom error logic here
            Console.WriteLine(args.ErrorContext.Error.Message);
            args.ErrorContext.Handled = true;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.3;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
